shingoinstitute/shingo-backend

routes/api/salesforce/affiliates/index.js

Added ability to pull Language_Specialties from SF for Affiliate Page of public website.

Update to getAffiliates SOQL Query

---

models/support/Feeback.js

Had to change the rating property of the Feedback model to be DataTypes.FLOAT to allow for incremental ratings.

Updated rating to float

---

routes/api/support/feedback.js

Forgot to change the route to parse rating as float instead of integer.

Needed to parse as float in route

---

routes/api/salesforce/events/venues.js

Needed to and the URL to get map image.

Added URL__c to getMaps in getVenue

---

routes/api/support/bugs.js
routes/api/support/feedback.js

Needed to disable GET routes for bugs and feedback to protect user emails.

Disabled get routes

---

routes/api/salesforce/events/sessions.js

Needed to have the room name in list view.

Added Room__r.Name to SOQL query

---

routes/api/salesforce/events/sessions.js

Added SF Id field to SOQL query

Had to add Id

---

routes/api/salesforce/events/sessions.js

Added more info to room so that deep linking could occur in the mobile apps.

Added more fields to room

---

routes/api/salesforce/events/sessions.js

Messed up the map coordinates. They are now separated into X and Y.

Fixed the map coord column names

---

routes/api/salesforce/events/sessions.js

Floor is needed to use right map.

Added Floor to Room query

---

routes/api/salesforce/events/venues.js

Added more to venues to assist in deep linking

---

routes/api/salesforce/events/sponsors.js

Added org id to sponsor soql query

---

routes/api/salesforce/events/index.js
routes/api/salesforce/events/sessions.js
routes/api/salesforce/events/speakers.js
routes/api/salesforce/events/sponsors.js
routes/api/salesforce/events/venues.js

Hotfix sessions

---

routes/api/salesforce/affiliates/facilitators.js
routes/api/salesforce/affiliates/index.js

- Added routes to build dynamic affiliate pages online.
NOTE: Page paths will soon be deprecated.  Affiliate pages can be found at shingo.org/affiliates/:id
id being the SF id of the affiliate

Added affiliate & facilitator routes

---

models/query.js
routes/api/salesforce/awards/index.js
routes/api/salesforce/awards/publication.js
routes/api/salesforce/index.js

- Added route for awards page
- Abstracted query function

Hotfix awards

---

Logger.js

Updated default log file name

---

routes/api/salesforce/events/index.js

* Video__c
* Logo__c
* Logo_Large__c
* Primary_Color__c
* Registration_Link__c
* Sales_Text__c

Added required fields

---

routes/api/salesforce/events/sponsors.js

If querying sponsors for a particular event we would also only want ads from that event as well. Added logic to add a where clause to the query.

Added filter for event id if it is passed

---

models/QueryBuilder.js
routes/api/salesforce/events/index.js

Added query builder and refactored events.index to use it.

Added query builder and refac events to use it

---

models/QueryBuilder.js
routes/api/salesforce/events/days.js
routes/api/salesforce/events/exhibitors.js
routes/api/salesforce/events/hotels.js
routes/api/salesforce/events/index.js
routes/api/salesforce/events/recipients.js
routes/api/salesforce/events/rooms.js
routes/api/salesforce/events/sessions.js
routes/api/salesforce/events/speakers.js
routes/api/salesforce/events/sponsors.js
routes/api/salesforce/events/venues.js

Refactored all SOQL queries to use query builder for better integration with git.

Refactored all SF queries to use query builder.

---

routes/api/salesforce/events/index.js

Added subquery for Shingo Travel Info objects on event detail.

Hotfix travelinfos

---

routes/api/salesforce/events/recipients.js

Added Name and Author(s) field to query

---

routes/api/salesforce/events/recipients.js

Patch to get publication info into correct location for iOS

---

routes/api/salesforce/events/index.js

Filtered out Cancelled attendees

---

routes/api/salesforce/awards/index.js

Added route for research award
